server:
  port: 4315
  servlet:
    context-path: /shoppingserver
#    application-display-name: shoppingserve


spring:
  datasource:
    url: jdbc:mysql://charjin.top:3306/online_shopping?useUnicode=true&characterEncoding=UTF-8
    #    url: jdbc:mysql:///online_shopping
    username: root
    password: char0414.
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: shoppingserver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

#  thymeleaf:
#    suffix: .html

mybatis:
  #  type-aliases-package: top.charjin.shoppingserver.entity
  mapper-locations: classpath:mybatis/mappers/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



#logging:
#  level:
#    com:
#      looedu:
#        mapper: debug
#
#    cn:
#      piesat:
#        mapper: debug