server:
  port: 4315
  servlet:
    context-path: /shoppingserver
#    application-display-name: shoppingserver

spring:
  datasource:
    url: jdbc:mysql://charjin.top:3306/OnlineShopping
    username: root
    password: char0414.
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: top.charjin.shoppingserver.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
